version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    networks:
      - app-network

  java:
    build: ./java
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge